# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-08 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('full_address', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('display_address', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('type_level', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.AddressType')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Address',
            },
        ),
    ]
