# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-08 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresstype',
            name='level',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
