# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-08 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_address_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
