# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-08 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_auto_20171008_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='type_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
