# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0007_cosmetologaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosmetologaddress',
            name='address_name',
        ),
        migrations.RemoveField(
            model_name='cosmetologaddress',
            name='cosmetolog_name',
        ),
        migrations.DeleteModel(
            name='CosmetologAddress',
        ),
    ]
