# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0009_addressaddfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='slug',
        ),
        migrations.AlterField(
            model_name='addressaddfile',
            name='address_file',
            field=models.FileField(upload_to='address_file_add/'),
        ),
    ]
