# Generated by Django 3.2.11 on 2023-03-11 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitemplus',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='stockitemplus',
            name='product_item',
        ),
        migrations.DeleteModel(
            name='StockFilePlus',
        ),
        migrations.DeleteModel(
            name='StockItemPlus',
        ),
    ]
