# Generated by Django 3.2.11 on 2023-03-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stocktotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitemplus',
            name='total_price_plus_uah',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockitemplus',
            name='total_price_plus_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
