# Generated by Django 3.2.11 on 2023-03-20 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20220718_1152'),
        ('stock', '0007_purchaseitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitemplus',
            name='id_purchase',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_purchase_item_plus', to='stock.purchaseitem'),
        ),
        migrations.CreateModel(
            name='StockItemPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_item', models.IntegerField(default=0)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_uah', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price_uah', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField(blank=True, default=None, null=True)),
                ('comments', models.CharField(blank=True, default=None, max_length=124, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('id_purchase', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_purchase_item', to='stock.purchaseitem')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_purchase_product_item', to='products.productitem')),
            ],
            options={
                'verbose_name': 'StockItemPurchase',
                'verbose_name_plural': 'StockItemPurchases',
            },
        ),
    ]
