# Generated by Django 3.2.11 on 2023-03-21 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20230320_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitemminus',
            name='id_purchase',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_purchase_item_minus', to='stock.purchaseitem'),
        ),
    ]
