# Generated by Django 3.2.11 on 2023-03-30 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220718_1152'),
        ('stock', '0010_stockitemplus_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitemminus',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productcategory'),
        ),
    ]
