# Generated by Django 3.2.11 on 2023-04-07 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_productinorder_due_date'),
        ('stock', '0013_auto_20230407_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitemreserved',
            old_name='num_minus',
            new_name='num_reserved',
        ),
        migrations.RemoveField(
            model_name='stockitemreserved',
            name='id_purchase',
        ),
        migrations.AddField(
            model_name='stockitemreserved',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
