# Generated by Django 3.2.11 on 2022-03-09 17:51

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosmetologs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=64)),
                ('name_sender', models.CharField(max_length=32)),
                ('email_sender', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('message', models.TextField(blank=True, default=None, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'LetterTemplate',
                'verbose_name_plural': 'LetterTemplates',
            },
        ),
        migrations.CreateModel(
            name='LogoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logo_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LogoPhoto',
                'verbose_name_plural': 'LogoPhotos',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('email_confirm', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('city', models.CharField(blank=True, default=None, max_length=56, null=True)),
                ('index', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('street', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('locality', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('tel_number', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('company_name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('nip', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('company_confirm', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MySubscriber',
                'verbose_name_plural': 'A lot of Subscribers',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('type', models.CharField(max_length=16)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('image', models.ImageField(default='../img/bg_image.png', upload_to='training/')),
                ('start_date', models.DateTimeField(default=None)),
                ('duration', models.CharField(max_length=8)),
                ('location', models.CharField(max_length=64)),
                ('audience', models.CharField(max_length=32)),
                ('goal', models.CharField(max_length=128)),
                ('agenda', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
                ('trainer', models.CharField(max_length=32)),
                ('total_place', models.IntegerField(blank=True, default=20, null=True)),
                ('registered_place', models.IntegerField(blank=True, default=None, null=True)),
                ('left_place', models.IntegerField(blank=True, default=None, null=True)),
                ('left_place_shown', models.IntegerField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
            },
        ),
        migrations.CreateModel(
            name='TrainingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_name', models.CharField(max_length=64)),
                ('trainee_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=False)),
                ('trainee_tel_number', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('tel_number_confirm', models.BooleanField(default=False)),
                ('registration_confirmed', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(max_length=32)),
                ('user_email', models.EmailField(max_length=254)),
                ('training', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.training')),
            ],
            options={
                'verbose_name': 'TrainingUser',
                'verbose_name_plural': 'TrainingUsers',
            },
        ),
        migrations.CreateModel(
            name='SubscriberCosmetolog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.IntegerField(blank=True, default=None, null=True)),
                ('cosmetolog_id', models.IntegerField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cosmetolog_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmetologs.cosmetolog')),
                ('subscriber_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.subscriber')),
            ],
            options={
                'verbose_name': 'SubscriberCosmetolog',
                'verbose_name_plural': 'SubscriberCosmetologs',
            },
        ),
        migrations.CreateModel(
            name='SliderMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=64)),
                ('ad_customer', models.CharField(max_length=64)),
                ('ad_description', models.TextField(blank=True, default=None, null=True)),
                ('ad_title', models.CharField(max_length=128)),
                ('ad_text', models.TextField(blank=True, default=None, null=True)),
                ('alt', models.CharField(default='Please', max_length=64)),
                ('image', models.ImageField(upload_to='slider_images/')),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=False)),
                ('position', models.IntegerField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('activation_date', models.DateField(blank=True, default=None)),
                ('deactivation_date', models.DateField(blank=True, default=None)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SliderMain',
                'verbose_name_plural': 'SliderMains',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=32)),
                ('is_main_menu', models.BooleanField(default=False)),
                ('rate_main_menu', models.IntegerField(blank=True, default=None, null=True)),
                ('page_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='LetterEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_receiver', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('letter_template_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.lettertemplate')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LetterEmail',
                'verbose_name_plural': 'LetterEmails',
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
                ('from_name', models.CharField(max_length=32)),
                ('email_sender', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('phone_sender', models.CharField(blank=True, default=None, max_length=13, null=True)),
                ('city_sender', models.CharField(max_length=32)),
                ('message', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('who_answer', models.CharField(max_length=64)),
                ('cosmetolog', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmetologs.cosmetolog')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='landing.lettertemplate')),
            ],
            options={
                'verbose_name': 'Letter',
                'verbose_name_plural': 'Letters',
            },
        ),
    ]
