# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-07 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'logo_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LogoPhoto',
                'verbose_name_plural': 'LogoPhotos',
            },
        ),
        migrations.CreateModel(
            name='SliderMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=64)),
                ('ad_customer', models.CharField(max_length=64)),
                ('ad_description', models.TextField(blank=True, default=None, null=True)),
                ('ad_title', models.CharField(max_length=128)),
                ('ad_text', models.TextField(blank=True, default=None, null=True)),
                ('image', models.ImageField(upload_to=b'advert_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('activation_date', models.DateField(blank=True, default=None)),
                ('deactivation_date', models.DateField(blank=True, default=None)),
            ],
            options={
                'verbose_name': 'SliderMain',
                'verbose_name_plural': 'SliderMains',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=128)),
                ('city', models.CharField(default=b'Unknown', max_length=56)),
            ],
            options={
                'verbose_name': 'MySubscriber',
                'verbose_name_plural': 'A lot of Subscribers',
            },
        ),
    ]
