# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='city',
            field=models.CharField(default=b'Unknown', max_length=56),
        ),
    ]
