# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-23 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidermain',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logoimage',
            name='image',
            field=models.ImageField(upload_to='logo_images/'),
        ),
        migrations.AlterField(
            model_name='slidermain',
            name='image',
            field=models.ImageField(upload_to='advert_images/'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='city',
            field=models.CharField(default='Unknown', max_length=56),
        ),
    ]
