# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-07 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20171023_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidermain',
            name='position',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
