# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-07 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20180303_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='location',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='email_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='index',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='locality',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='street',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='city',
            field=models.CharField(default=None, max_length=56),
        ),
    ]
