# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_logoimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=64)),
                ('ad_customer', models.CharField(max_length=64)),
                ('ad_description', models.TextField(blank=True, default=None, null=True)),
                ('ad_title', models.CharField(max_length=128)),
                ('ad_text', models.TextField(blank=True, default=None, null=True)),
                ('image', models.ImageField(upload_to=b'advert_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('activation_date', models.DateField(blank=True, default=None)),
                ('deactivation_date', models.DateField(blank=True, default=None)),
            ],
            options={
                'verbose_name': 'SliderMain',
                'verbose_name_plural': 'SliderMains',
            },
        ),
    ]
