# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-11 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20180311_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='index',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='tel_number',
            field=models.CharField(blank=True, default=None, max_length=11, null=True),
        ),
    ]
