# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-11 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20180311_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='company_name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='nip',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
