# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-11 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20180311_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='index',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
    ]
