# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-11 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_auto_20180311_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=56, null=True),
        ),
    ]
