# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-11 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_auto_20180311_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='company_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
