# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-08 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_subscriber_company_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
                ('from_name', models.CharField(max_length=32)),
                ('email_sender', models.EmailField(max_length=254)),
                ('city_sender', models.CharField(max_length=32)),
                ('message', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(max_length=32)),
                ('user_email', models.EmailField(max_length=254)),
                ('who_answer', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Letter',
                'verbose_name_plural': 'Letters',
            },
        ),
    ]
