# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-11 18:07
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=32)),
                ('is_main_menu', models.BooleanField(default=False)),
                ('rate_main_menu', models.IntegerField(blank=True, default=None, null=True)),
                ('page_text', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Letter',
                'verbose_name_plural': 'Letters',
            },
        ),
    ]
