# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-22 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0019_traininguser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traininguser',
            old_name='email_confirm',
            new_name='is_active',
        ),
    ]
