# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-22 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0020_auto_20180422_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='left_place_shown',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='total_place',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
