# Generated by Django 2.1.4 on 2019-02-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0021_auto_20180422_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='phone_sender',
            field=models.CharField(blank=True, default=None, max_length=13, null=True),
        ),
    ]
