# Generated by Django 2.1.4 on 2019-02-21 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0024_auto_20190221_1925'),
        ('landing', '0022_letter_phone_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberCosmetolog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.IntegerField(blank=True, default=None, null=True)),
                ('cosmetolog_id', models.IntegerField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cosmetolog_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmetologs.Cosmetolog')),
                ('subscriber_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.Subscriber')),
            ],
            options={
                'verbose_name': 'SubscriberCosmetolog',
                'verbose_name_plural': 'SubscriberCosmetologs',
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='cosmetolog',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmetologs.Cosmetolog'),
        ),
        migrations.AddField(
            model_name='letter',
            name='cosmetolog_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='email_sender',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
