# Generated by Django 2.1.4 on 2019-02-22 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0023_auto_20190221_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_receiver', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LetterEmail',
                'verbose_name_plural': 'LetterEmails',
            },
        ),
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=64)),
                ('name_sender', models.CharField(max_length=32)),
                ('email_sender', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('message', models.TextField(blank=True, default=None, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'LetterTemplate',
                'verbose_name_plural': 'LetterTemplates',
            },
        ),
        migrations.AddField(
            model_name='letteremail',
            name='letter_template_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.LetterTemplate'),
        ),
    ]
