# Generated by Django 3.2.11 on 2022-01-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0024_auto_20190222_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidermain',
            name='alt',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
