# Generated by Django 3.2.11 on 2022-01-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0025_slidermain_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidermain',
            name='alt',
            field=models.CharField(default='Please', max_length=64),
        ),
    ]
