# Generated by Django 3.2.11 on 2022-01-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0028_slidermain_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidermain',
            name='image',
            field=models.ImageField(upload_to='slider_images/'),
        ),
    ]
