# Generated by Django 3.2.11 on 2022-02-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0029_alter_slidermain_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'LetterType',
                'verbose_name_plural': 'LetterTypes',
            },
        ),
    ]
