# Generated by Django 3.2.11 on 2022-02-14 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0030_lettertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='landing.lettertype'),
        ),
    ]
