# Generated by Django 3.2.11 on 2022-02-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0032_alter_letter_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LetterType',
        ),
    ]
