# Generated by Django 3.2.11 on 2022-02-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0035_remove_letter_cosmetolog_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='user_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
