# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(upload_to='blogs_images/'),
        ),
    ]
