# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-25 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='short_content',
            new_name='main_short_content',
        ),
        migrations.AddField(
            model_name='blog',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='main_short_content_01',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='main_short_content_02',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
