# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20170925_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='code',
            field=models.SlugField(default=django.utils.timezone.now, max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='code',
            field=models.SlugField(default=django.utils.timezone.now, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='h1',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
