# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20171006_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='code',
            field=models.SlugField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='code',
            field=models.SlugField(max_length=32, null=True, unique=True),
        ),
    ]
