# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20171006_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='code',
            field=models.SlugField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='code',
            field=models.SlugField(max_length=32, null=True),
        ),
    ]
