# Generated by Django 3.2.11 on 2022-02-28 07:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherTrick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AnotherTrick',
                'verbose_name_plural': 'AnotherTrick',
            },
        ),
        migrations.CreateModel(
            name='CalendarTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_name', models.CharField(max_length=64)),
                ('date_picked_from', models.DateTimeField()),
                ('date_picked_until', models.DateTimeField()),
                ('comments', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CalendarTraining',
                'verbose_name_plural': 'CalendarTraining',
            },
        ),
        migrations.CreateModel(
            name='ProductFileCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=64)),
                ('document', models.FileField(upload_to='another_documents/')),
                ('is_active', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ProductFileCSV',
                'verbose_name_plural': 'ProductFileCSVs',
            },
        ),
        migrations.CreateModel(
            name='TestEditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'TestEditor',
                'verbose_name_plural': 'TestEditors',
            },
        ),
    ]
