# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-19 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('another', '0002_auto_20180425_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilecsv',
            name='document',
            field=models.FileField(default=1, upload_to='another_documents/'),
            preserve_default=False,
        ),
    ]
