# Generated by Django 2.1.4 on 2019-01-18 17:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('another', '0003_productfilecsv_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'TestEditor',
                'verbose_name_plural': 'TestEditors',
            },
        ),
    ]
