# Generated by Django 3.0.5 on 2020-04-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('another', '0004_testeditor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_name', models.CharField(max_length=64)),
                ('date_picked_from', models.DateTimeField()),
                ('date_picked_until', models.DateTimeField()),
                ('comments', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CalendarTraining',
                'verbose_name_plural': 'CalendarTraining',
            },
        ),
    ]
