# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-07 11:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryForCosmetolog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CategoryForCosmetolog',
                'verbose_name_plural': 'CategoriesForCosmetolog',
            },
        ),
        migrations.CreateModel(
            name='Cosmetolog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('order_email', models.EmailField(max_length=254)),
                ('order_phone', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('logo_image', models.ImageField(upload_to=b'logo_images/')),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description_region', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description_tariff', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('headline', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('rating', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('order_nmb', models.IntegerField(default=0)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_active', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('registration_time', models.DateTimeField(blank=True, default=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('site_url', models.URLField()),
                ('active_until', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cosmetolog',
                'verbose_name_plural': 'Cosmetologs',
            },
        ),
        migrations.CreateModel(
            name='CosmetologCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmetologs.CategoryForCosmetolog')),
                ('cosmetolog', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmetologs.Cosmetolog')),
            ],
            options={
                'verbose_name': 'CosmetologCategory',
                'verbose_name_plural': 'CosmetologCategories',
            },
        ),
        migrations.CreateModel(
            name='ServiceProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('price01', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price02', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_avg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_action', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('short_description', models.TextField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmetologs.CategoryForCosmetolog')),
                ('cosmetolog', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmetologs.Cosmetolog')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ServiceProduct',
                'verbose_name_plural': 'ServiceProducts',
            },
        ),
        migrations.CreateModel(
            name='ServiceProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'products_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('service_product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmetologs.ServiceProduct')),
            ],
            options={
                'verbose_name': 'ServiceProductPhoto',
                'verbose_name_plural': 'ServiceProductPhotos',
            },
        ),
    ]
