# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-07 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproduct',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
