# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-21 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0003_cosmetologaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetolog',
            name='logo_image',
            field=models.ImageField(upload_to='logo_images/'),
        ),
        migrations.AlterField(
            model_name='serviceproductimage',
            name='image',
            field=models.ImageField(upload_to='products_images/'),
        ),
    ]
