# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0004_auto_20171021_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryForCosmetolog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmetologs.CategoryForCosmetolog')),
            ],
            options={
                'verbose_name': 'SubCategoryForCosmetolog',
                'verbose_name_plural': 'SubCategoriesForCosmetolog',
            },
        ),
    ]
