# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0007_cosmetologcategory_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproduct',
            name='subcategory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmetologs.SubCategoryForCosmetolog'),
        ),
    ]
