# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-19 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0009_auto_20180519_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetolog',
            name='logo_image',
            field=models.ImageField(help_text='optimal size  600x450', upload_to='logo_images/'),
        ),
    ]
