# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-29 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0010_auto_20180519_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosmetologType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CosmetologType',
                'verbose_name_plural': 'CosmetologTypes',
            },
        ),
        migrations.AddField(
            model_name='cosmetolog',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmetologs.CosmetologType'),
        ),
    ]
