# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-29 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0011_auto_20180529_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cosmetologtype',
            old_name='type_name',
            new_name='name',
        ),
    ]
