# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-31 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0012_auto_20180529_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetolog',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='краткое описание, 70 симоволов, которых будет на шот-рекламе', max_length=255, null=True),
        ),
    ]
