# Generated by Django 2.1 on 2018-09-13 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0021_auto_20180422_2232'),
        ('cosmetologs', '0014_auto_20180621_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberCosmetolog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.IntegerField(blank=True, default=None, null=True)),
                ('cosmetolog_id', models.IntegerField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cosmetolog_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmetologs.Cosmetolog')),
                ('subscriber_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.Subscriber')),
            ],
            options={
                'verbose_name': 'SubscriberCosmetolog',
                'verbose_name_plural': 'SubscriberCosmetologs',
            },
        ),
    ]
