# Generated by Django 2.1 on 2018-10-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0015_subscribercosmetolog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetolog',
            name='order_phone',
            field=models.CharField(blank=True, default=None, max_length=13, null=True),
        ),
    ]
