# Generated by Django 2.1 on 2018-10-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0016_auto_20181026_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetolog',
            name='site_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
