# Generated by Django 2.1.4 on 2018-12-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0017_auto_20181026_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetolog',
            name='city_cosmetolog',
            field=models.CharField(blank=True, default=None, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='cosmetolog',
            name='house_cosmetolog',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='cosmetolog',
            name='index_cosmetolog',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cosmetolog',
            name='street_cosmetolog',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
