# Generated by Django 2.1.4 on 2018-12-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0019_auto_20181215_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceaddfile',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='ServiceAddFile',
        ),
    ]
