# Generated by Django 2.1.4 on 2019-01-18 16:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0020_auto_20181221_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproduct',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
