# Generated by Django 2.1.4 on 2019-01-25 20:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0021_auto_20190118_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetolog',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=None, help_text='краткое описание, 70 симоволов, которых будет на шот-рекламе', null=True),
        ),
    ]
