# Generated by Django 2.1.4 on 2019-02-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0022_auto_20190125_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetolog',
            name='working_hours',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
