# Generated by Django 2.1.4 on 2019-02-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0023_cosmetolog_working_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribercosmetolog',
            name='cosmetolog_name',
        ),
        migrations.RemoveField(
            model_name='subscribercosmetolog',
            name='subscriber_name',
        ),
        migrations.DeleteModel(
            name='SubscriberCosmetolog',
        ),
    ]
