# Generated by Django 2.1.4 on 2019-03-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0024_auto_20190221_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosmetolog',
            name='city_cosmetolog',
        ),
        migrations.RemoveField(
            model_name='cosmetolog',
            name='street_cosmetolog',
        ),
    ]
