# Generated by Django 2.1.4 on 2019-03-02 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0010_auto_20171012_1843'),
        ('cosmetologs', '0025_auto_20190302_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetolog',
            name='city_cosmetolog',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.Address'),
        ),
        migrations.AddField(
            model_name='cosmetolog',
            name='street_cosmetolog',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='street_cosmetolog', to='addresses.Address'),
        ),
    ]
