# Generated by Django 2.1.4 on 2019-03-04 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0026_auto_20190302_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetologaddress',
            name='service_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cosmetologaddress',
            name='service_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmetologs.ServiceProduct'),
        ),
    ]
