# Generated by Django 2.1.4 on 2019-03-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0027_auto_20190304_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetologaddress',
            name='city_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='cosmetologaddress',
            name='district_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='cosmetologaddress',
            name='street_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
