# Generated by Django 2.2.5 on 2019-10-31 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0030_cosmetologaddfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cosmetologaddfile',
            options={'verbose_name': 'CosmetologAddFile', 'verbose_name_plural': 'CosmetologAddFiles'},
        ),
    ]
