# Generated by Django 2.2.5 on 2019-10-31 10:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0031_auto_20191031_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetolog',
            name='working_hours',
            field=ckeditor.fields.RichTextField(blank=True, default=None, help_text='указать дни недели и время от и до - Понедельник 10:00 -15:00', null=True),
        ),
    ]
