# Generated by Django 2.2.5 on 2019-11-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0032_auto_20191031_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetolog',
            name='type_text',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
