# Generated by Django 2.2.5 on 2019-11-08 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosmetologs', '0033_cosmetolog_type_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproduct',
            name='duration',
            field=models.CharField(blank=True, default=None, max_length=18, null=True),
        ),
        migrations.CreateModel(
            name='ServiceAddFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, default=None, max_length=124, null=True)),
                ('service_file', models.FileField(upload_to='product_file_add/')),
                ('is_active', models.BooleanField(default=False)),
                ('start_import', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ServiceAddFile',
                'verbose_name_plural': 'ServiceAddFiles',
            },
        ),
    ]
