# Generated by Django 2.2.5 on 2019-11-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0034_auto_20191108_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproduct',
            name='price01',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='serviceproduct',
            name='price02',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
