# Generated by Django 3.2.11 on 2023-08-28 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cosmetologs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSumStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(blank=True, default=None, max_length=2, null=True, unique=True)),
                ('name', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'BalanceSumStatus',
                'verbose_name_plural': 'BalanceSumStatuses',
            },
        ),
        migrations.CreateModel(
            name='BonusAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(blank=True, default=None, max_length=2, null=True, unique=True)),
                ('name', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('uah_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('usd_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'BonusAccount',
                'verbose_name_plural': 'BonusAccounts',
            },
        ),
        migrations.CreateModel(
            name='BonusAccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(blank=True, default=None, max_length=2, null=True, unique=True)),
                ('name', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'BonusAccountType',
                'verbose_name_plural': 'BonusAccountTypes',
            },
        ),
        migrations.CreateModel(
            name='BonusEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(blank=True, default=None, max_length=2, null=True, unique=True)),
                ('name', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'BonusEventType',
                'verbose_name_plural': 'BonusEventTypes',
            },
        ),
        migrations.CreateModel(
            name='BonusAccountCosmetolog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_sum', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('balance_sum_status', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bonuses.balancesumstatus')),
                ('bonus_account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bonuses.bonusaccount')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmetologs.cosmetolog')),
            ],
            options={
                'verbose_name': 'BonusAccount',
                'verbose_name_plural': 'BonusAccounts',
            },
        ),
        migrations.AddField(
            model_name='bonusaccount',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bonuses.bonusaccounttype'),
        ),
    ]
