# Generated by Django 3.2.11 on 2023-08-30 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0004_bonusaccountevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusaccountevent',
            name='event_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bonuses.bonuseventtype'),
        ),
    ]
