# Generated by Django 3.2.11 on 2023-08-31 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0005_bonusaccountevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusEvenStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(blank=True, default=None, max_length=2, null=True, unique=True)),
                ('name', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'BonusEvenStatus',
                'verbose_name_plural': 'BonusEvenStatuses',
            },
        ),
        migrations.AddField(
            model_name='bonusaccountevent',
            name='event_status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bonuses.bonusevenstatus'),
        ),
    ]
