# Generated by Django 3.2.11 on 2023-08-31 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0006_auto_20230831_1330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BonusEvenStatus',
            new_name='BonusEventStatus',
        ),
        migrations.AlterModelOptions(
            name='bonuseventstatus',
            options={'verbose_name': 'BonusEventStatus', 'verbose_name_plural': 'BonusEventStatuses'},
        ),
    ]
