# Generated by Django 3.2.11 on 2023-09-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0007_auto_20230831_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusaccountcosmetolog',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bonusaccountcosmetolog',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
