# Generated by Django 3.2.11 on 2023-04-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_productinbasket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
