# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-21 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20171021_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='session_key',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
