# Generated by Django 3.2.11 on 2023-09-13 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0008_auto_20230908_0920'),
        ('orders', '0004_productinorder_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cosmetolog_bonus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bonuses.bonusaccountcosmetolog'),
        ),
    ]
