# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-21 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0004_auto_20171021_1853'),
        ('orders', '0004_serviceorder_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='service_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='service_product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmetologs.ServiceProduct'),
        ),
    ]
