# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-21 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_serviceorder_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='service_product',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
