# Generated by Django 2.1.4 on 2019-02-26 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0024_auto_20190221_1925'),
        ('orders', '0009_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='total_price',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='cosmetolog',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='cosmetolog_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='cosmetolog_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmetologs.Cosmetolog'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='customer_city',
            field=models.CharField(blank=True, default=None, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='price01',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='price02',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
