# Generated by Django 2.1.4 on 2019-02-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190226_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
