# Generated by Django 3.2.11 on 2022-02-07 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetologs', '0039_auto_20220206_1328'),
        ('orders', '0012_alter_productinbasket_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_address',
            new_name='receiver_delivery_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_email',
            new_name='receiver_email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='cosmetolog',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmetologs.cosmetolog'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_father_name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_phone',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_surname',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
