# Generated by Django 3.2.11 on 2022-02-08 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_productitemsales_exchange_rate'),
        ('orders', '0013_auto_20220207_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productitemsales'),
        ),
    ]
