# Generated by Django 3.2.11 on 2022-02-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_productinorder_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='StatusOrder',
        ),
    ]
