# Generated by Django 3.2.11 on 2022-02-11 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20220209_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusorder',
            name='status_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.statuspayment'),
        ),
    ]
