# Generated by Django 3.2.11 on 2022-02-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_productitemsales_product_item'),
        ('orders', '0019_auto_20220211_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='bundle',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.bundlesale'),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='bundle',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.bundlesale'),
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productitemsales'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productitemsales'),
        ),
    ]
