# Generated by Django 3.2.11 on 2022-03-09 17:51

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_price_uah', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('usd_rate_initial', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('usd_rate_correct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('usd_rate_before', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('date_before', models.DateTimeField(blank=True, default=None, null=True)),
                ('usd_diff', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CurrencyExchange',
                'verbose_name_plural': 'CurrencyExchange',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(blank=True, default='Shor', max_length=64, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('name_pl', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('name_description', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('name_description_1', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('description_1', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
                ('name_description_2', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('description_2', models.TextField(blank=True, default=None, null=True)),
                ('name_description_3', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('description_3', models.TextField(blank=True, default=None, null=True)),
                ('name_description_4', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('description_4', models.TextField(blank=True, default=None, null=True)),
                ('name_description_5', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('description_5', models.TextField(blank=True, default=None, null=True)),
                ('short_description', models.TextField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('slug', models.SlugField(max_length=16, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_category_logo_image', models.ImageField(default='logo_images/DK_logo.png', help_text='optimal size  600x450 - Need to be checked', upload_to='logo_images/')),
                ('product_category_page_image', models.ImageField(default='logo_images/DK_logo.png', help_text='optimal size  600x450 - Need to be checked', upload_to='logo_images/')),
            ],
            options={
                'verbose_name': 'CategoryProduct',
                'verbose_name_plural': 'CategoryProducts',
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('volume_equivalent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productcategory')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
            ],
            options={
                'verbose_name': 'ProductItem',
                'verbose_name_plural': 'ProductItem',
            },
        ),
        migrations.CreateModel(
            name='ProductJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ProductJoin',
                'verbose_name_plural': 'ProductJoin',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('slug', models.SlugField(max_length=16, unique=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ProductType',
                'verbose_name_plural': 'ProductTypes',
            },
        ),
        migrations.CreateModel(
            name='ProductVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ProductVolume',
                'verbose_name_plural': 'ProductVolumes',
            },
        ),
        migrations.CreateModel(
            name='ProductVolumeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ProductVolumeType',
                'verbose_name_plural': 'ProductVolumeTypes',
            },
        ),
        migrations.CreateModel(
            name='SalesProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SalesProductType',
                'verbose_name_plural': 'SalesProductTypes',
            },
        ),
        migrations.CreateModel(
            name='SalesProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, default=0, null=True)),
                ('name_sales', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('name_pl', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('slug', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('price_old', models.IntegerField(default=0)),
                ('price_current', models.IntegerField(default=0)),
                ('price_old_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_current_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='sales_images/')),
                ('image_url', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('duplicate', models.IntegerField(default=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('exchange_rate', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.currencyexchange')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.salesproducttype')),
            ],
            options={
                'verbose_name': 'SalesProduct',
                'verbose_name_plural': 'SalesProducts',
            },
        ),
        migrations.CreateModel(
            name='SaleProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product_item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_item', to='products.productitem')),
                ('sales_product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_product', to='products.salesproduct')),
            ],
            options={
                'verbose_name': 'SaleProductItem',
                'verbose_name_plural': 'SaleProductItems',
            },
        ),
        migrations.AddField(
            model_name='productitem',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.producttype'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='volume',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productvolume'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='volume_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productvolumetype'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='ProductAddFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, default=None, max_length=124, null=True)),
                ('what_to_do', models.CharField(choices=[('Add_Product_Item', 'Add_Product_Item'), ('Add_Product_Join', 'Add_Product_Join'), ('Add_Nothing', 'Add_Nothing')], default='Add_Nothing', max_length=16)),
                ('product_file', models.FileField(upload_to='product_file_add/')),
                ('is_active', models.BooleanField(default=False)),
                ('start_import', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ProductAddFile',
                'verbose_name_plural': 'ProductAddFiles',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productcategory'),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('name_pl', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('slug', models.SlugField(max_length=16, unique=True)),
                ('name_description', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='ingredient_images/')),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.salesproducttype')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
    ]
