# Generated by Django 3.2.11 on 2022-03-10 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='type',
        ),
        migrations.CreateModel(
            name='IngredientProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.ingredient')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
            ],
            options={
                'verbose_name': 'IngredientProduct',
                'verbose_name_plural': 'IngredientProducts',
            },
        ),
    ]
