# Generated by Django 3.2.11 on 2022-07-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesproduct',
            name='auto_calculation_visitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesproduct',
            name='diff_cosmo_visitor',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='salesproduct',
            name='price_visitor_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesproduct',
            name='price_visitor_old',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesproduct',
            name='price_visitor_show',
            field=models.BooleanField(default=False),
        ),
    ]
