# Generated by Django 3.2.11 on 2022-03-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220310_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ref_number',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productaddfile',
            name='what_to_do',
            field=models.CharField(choices=[('Add_Product_Item', 'Add_Product_Item'), ('Add_Product_Join', 'Add_Product_Join'), ('Add_Ingredient_Item', 'Add_Ingredient_Item'), ('Add_IngredientProduct_Join', 'Add_IngredientProduct_Join'), ('Add_Nothing', 'Add_Nothing')], default='Add_Nothing', max_length=32),
        ),
    ]
