# Generated by Django 3.2.11 on 2022-03-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220310_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_ref_number',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
    ]
