# Generated by Django 3.2.11 on 2022-03-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_product_ref_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaddfile',
            name='what_to_do',
            field=models.CharField(choices=[('Add_Product_Item', 'Add_Product_Item'), ('Add_Ingredient_Item', 'Add_Ingredient_Item'), ('Add_IngredientProduct_Join', 'Add_IngredientProduct_Join'), ('Add_Product_Sale', 'Add_Product_Sale'), ('Add_Nothing', 'Add_Nothing')], default='Add_Nothing', max_length=32),
        ),
        migrations.AlterField(
            model_name='salesproduct',
            name='rank',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
