# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170606_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='price',
        ),
    ]
