# Generated by Django 3.2.11 on 2022-03-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220316_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienttype',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.salesproducttype'),
        ),
    ]
