# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-26 07:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_auto_20180519_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAddFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, default=None, max_length=124, null=True)),
                ('product_file', models.FileField(upload_to='product_file_add/')),
                ('is_active', models.BooleanField(default=False)),
                ('start_import', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ProductAddFile',
                'verbose_name_plural': 'ProductAddFiles',
            },
        ),
    ]
