# Generated by Django 3.2.11 on 2022-03-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_ingredienttype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredienttype',
            name='type',
        ),
    ]
