# Generated by Django 2.1.4 on 2019-02-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180529_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='partner',
            new_name='cosmetolog',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
