# Generated by Django 3.2.11 on 2022-03-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_ingredienttype_type_ref_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(max_length=16),
        ),
    ]
