# Generated by Django 4.0 on 2022-01-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190219_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_old',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
