# Generated by Django 3.2.11 on 2022-03-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_ingredient_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttype',
            name='type_ref_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
