# Generated by Django 4.0 on 2022-01-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_price_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='product_category_logo_image',
            field=models.ImageField(default='logo_images/Светлана Лескова.png', help_text='optimal size  600x450 - Need to be checked', upload_to='logo_images/'),
        ),
    ]
