# Generated by Django 3.2.11 on 2022-03-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_ingredienttype_type_ref_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='slug',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
