# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20170923_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.SlugField(default=django.utils.timezone.now, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='code',
            field=models.SlugField(default=django.utils.timezone.now, max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
