# Generated by Django 3.2.11 on 2022-01-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productcategory_product_category_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='product_category_page_image',
            field=models.ImageField(default='logo_images/DK_logo.png', help_text='optimal size  600x450 - Need to be checked', upload_to='logo_images/'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='product_category_logo_image',
            field=models.ImageField(default='logo_images/DK_logo.png', help_text='optimal size  600x450 - Need to be checked', upload_to='logo_images/'),
        ),
    ]
