# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20171006_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='code',
        ),
    ]
