# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20171006_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.SlugField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='code',
            field=models.SlugField(max_length=16, null=True, unique=True),
        ),
    ]
