# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20171006_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.SlugField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='code',
            field=models.SlugField(max_length=16, null=True),
        ),
    ]
