# Generated by Django 3.2.11 on 2022-01-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productaddfile_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productaddfile',
            old_name='title',
            new_name='what_to_do',
        ),
    ]
