# Generated by Django 3.2.11 on 2022-01-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_title_productaddfile_what_to_do'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cosmetolog',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_old',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='product',
            name='volume_equivalent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='volume_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='ref_number',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
