# Generated by Django 3.2.11 on 2022-01-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20220126_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ref_number',
        ),
    ]
