# Generated by Django 3.2.11 on 2022-01-26 12:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_product_ref_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_1',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(blank=True, default='Shor', max_length=64, null=True),
        ),
    ]
