# Generated by Django 3.2.11 on 2022-01-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20220126_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
