# Generated by Django 3.2.11 on 2022-02-02 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20220126_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItemSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_old', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_current', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product_item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productitem')),
            ],
            options={
                'verbose_name': 'ProductItemSales',
                'verbose_name_plural': 'ProductItemSales',
            },
        ),
    ]
