# Generated by Django 3.2.11 on 2022-02-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_productitemsales'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitemsales',
            name='price_current_usb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productitemsales',
            name='price_current_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
