# Generated by Django 3.2.11 on 2022-02-06 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0025_currencyexchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitemsales',
            old_name='price_current_usb',
            new_name='price_old_usd',
        ),
        migrations.AddField(
            model_name='productitemsales',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
