# Generated by Django 3.2.11 on 2022-02-06 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20220206_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitemsales',
            name='exchange_rate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.currencyexchange'),
        ),
    ]
