# Generated by Django 3.2.11 on 2022-02-06 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_productitemsales_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitemsales',
            name='exchange_rate',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.currencyexchange'),
        ),
    ]
