# Generated by Django 3.2.11 on 2022-02-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_productitemsales_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyexchange',
            name='date_before',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyexchange',
            name='usd_diff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='currencyexchange',
            name='usd_rate_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='currencyexchange',
            name='usd_rate_correct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='currencyexchange',
            name='usd_rate_initial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
