# Generated by Django 3.2.11 on 2022-02-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20220208_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSalesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ProductSalesType',
                'verbose_name_plural': 'ProductSalesTypes',
            },
        ),
    ]
