# Generated by Django 3.2.11 on 2022-02-16 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0030_productsalestype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('name_pl', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('price_old', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_current', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_old_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_current_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='bundles_images/')),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('exchange_rate', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.currencyexchange')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BundleSale',
                'verbose_name_plural': 'BundleSales',
            },
        ),
        migrations.AlterModelOptions(
            name='productitemsales',
            options={'verbose_name': 'ProductItemSale', 'verbose_name_plural': 'ProductItemSales'},
        ),
        migrations.AlterField(
            model_name='productitemsales',
            name='exchange_rate',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.currencyexchange'),
        ),
        migrations.AlterField(
            model_name='productitemsales',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productitemsales',
            name='product_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productitem'),
        ),
        migrations.CreateModel(
            name='ProductInBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.bundlesale')),
                ('product_item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productitem')),
            ],
            options={
                'verbose_name': 'ProductInBundle',
                'verbose_name_plural': 'ProductInBundles',
            },
        ),
    ]
