# Generated by Django 3.2.11 on 2022-02-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20220216_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitemsales',
            name='product_item',
        ),
    ]
