# Generated by Django 3.2.11 on 2022-02-16 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_remove_productitemsales_product_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitemsales',
            name='product_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productitem'),
        ),
    ]
